[tool.poetry]
name = "pydantic-partial"
version = "0.1.0"
description = "Create partial models from your pydantic models. Partial models may allow None for certain or all fields."
authors = ["TEAM23 GmbH <info@team23.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
pydantic = ">=1.9.0<2.0.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"
pytest-coverage = "^0.0"
isort = "^5.10.1"
mypy = "^0.971"
flake8 = "^5.0.4"

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
line_length = 115

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
