[tool.poetry]
name = "pydantic-partial"
version = "0.1.0"
description = "Create partial models from your pydantic models. Partial models may allow None for certain or all fields."
authors = ["TEAM23 GmbH <info@team23.de>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
